# Generated by Django 4.1.7 on 2023-03-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=100000)),
                ('price', models.CharField(default=False, max_length=100000)),
                ('bedRooms', models.CharField(default=False, max_length=100000)),
                ('bathRooms', models.CharField(default=False, max_length=100000)),
                ('sqft', models.CharField(default=False, max_length=100000)),
                ('maxGuests', models.CharField(default=False, max_length=100000)),
                ('description', models.CharField(default=False, max_length=100000)),
                ('ratings', models.FloatField(default=False, max_length=100000)),
                ('reviews', models.CharField(default=False, max_length=100000)),
            ],
        ),
    ]
