# Generated by Django 4.1.7 on 2023-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_house_city_house_state_house_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img_url',
            field=models.CharField(default=False, max_length=100000),
        ),
    ]
