# Generated by Django 4.1.7 on 2023-03-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_house_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='city',
            new_name='cityValue',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='img_url',
            new_name='img_URL',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='state',
            new_name='stateValue',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='zip',
            new_name='zipCode',
        ),
    ]
