# Generated by Django 4.1.7 on 2023-03-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_city_house_cityvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cityValue',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='house',
            name='img_URL',
            field=models.CharField(default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='house',
            name='stateValue',
            field=models.CharField(default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='zipCode',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
