# Generated by Django 4.1.7 on 2023-03-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_house_cityvalue_alter_house_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cityValue',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img_URL',
        ),
        migrations.RemoveField(
            model_name='house',
            name='stateValue',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zipCode',
        ),
    ]
