# Generated by Django 4.1.7 on 2023-03-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_house_cityvalue_remove_house_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='sqft',
            new_name='location',
        ),
    ]
