# Generated by Django 4.1.7 on 2023-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_house_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='reviews',
            field=models.CharField(default=False, max_length=100000),
        ),
    ]
