# Generated by Django 4.1.7 on 2023-04-04 17:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_house_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='reviews',
            field=jsonfield.fields.JSONField(),
        ),
    ]
